### ISSUE TITLE
ABCI 2.0: Final adjustments

### ISSUE THREAD

**Issue by sergio-mena** [cometbft/cometbft#10]
Tasks:

  - [x] #8
  - [x] #90
    - see what is missing from tendermint/tendermint#8158
  - [x] #97
  - [x] Double-check if there is something we need from tendermint/tendermint#8414 (probably not)
  - [x] #471 (backport leftovers to `v0.37.x` #479)
    - see what metrics we are still missing from tendermint/tendermint#8480 (mainly vote extensions)
  - [x] Redundant params in `FinalizeBlock`, and obsolete methods (`BeginBlock`, etc). Double check that changes in tendermint/tendermint#8598 and/or tendermint/tendermint#8633 are unnecessary
  - [x] #478
    - move `app_hash` from `Commit` to `FinalizeBlock`: follow tendermint/tendermint#8664
  - [x] #488
  - [x] #490
  - [x] #485
  - [x] Leftovers
    - #514 
    - #515
  - [x] Bugfixes
    - #539
    - #542
    - #546
    - #562
  - [x] #547
  - [x] Once we are code complete, and all CI tests pass, merge branch back into `main`
    - #568
    - #572
  - [x] #510
  - [x] Second part of #409 (remove config to disable blocksync)

DoD:

  - No errors in CI
  - No major concerns if testnets were run
  - Branch `feature/abci++vef` has been merged back into `main`

Original issue: tendermint/tendermint#9916

**Comment by sergio-mena** [comment]
Closing as all tasks have been completed
