### ISSUE TITLE
storage: Alternative representation of the genesis file.

### ISSUE THREAD

**Issue by jmalicevic** [cometbft/cometbft#1037]
The genesis file is stored as a value in CometBFTs kv store. As the file can be large it can hit the internal file size limitations of databases. 

We need to figure out an alternative representation of this file. A proposal was to store the hash of the genesis file in the state store but the actual file is stored outside the store. 

Existing PRs targetting this :
- #1017 
Historically, this issue was mentioned in the original Tendermint repository under:
   - tendermint/tendermint#8416
   - tendermint/tendermint#6563

A potentially related problem is that at the moment the Genesis file is retrievable via RPC. Even though it is retrieved in chunks, it is still loaded entirely into memory before it is chunked up. We could improve on this if we take it into consideration. 

Things to understand and complete as part of this issue: 
* [x] #1286
* [x] #1078

After discussing, this issue will be addressed in two phases:

### Phase I 

* [x] Remove the genesis file from the kvstore and store it in an external file.
  * [x] Adopt PR #1017.
  * [x] #1287
  * [x] #1259

### Phase II
- [x] Reduce genesis's memory footprint: #1290

### Phase III
- [x] Optimize chunking logic (from storage and RPC perspective): #1289
  - [x] Reduce genesis chunks size: #4298 

### DoD

* [x] Genesis file is not stored as one entry in the state store
* [x] Tests written to confirm no errors are generated for large genesis files
* [x] Document how the genesis file is stored and represented
* [x] (stretch) Improve retrieval of Genesis file when requested via RPC

**Comment by andynog** [comment]
Not sure if this would be also part of this issue, but I believe we need to better understand the use cases for people retrieving the genesis file via RPC, maybe we can provide another way to query parts of it only or something that returns like a hash that people can compare to another hash from a file retrieved from a different source (e.g. Github)

**Comment by mzabaluev** [comment]
It's sad that the `/genesis_chunked` endpoint has to exist in the form it is. Because it's JSON-RPC, the protocol cannot do the usual HTTP thing: use the `Range` header on a `genesis` GET endpoint. That can also enable off-the-shelf caching/CDN solutions that abundantly exist for HTTP web services.

Or maybe, we can serve the genesis endpoint over plain HTTP and deprecate the JSON-RPC one? It could even be a start of converting the entire RPC to plain REST, which you can route and load-balance with off-the-shelf cloud components when things like [ADR 102](https://github.com/cometbft/cometbft/issues/707) are realized.
What value does the JSON-RPC framing deliver in our service?

**Comment by alesforz** [comment]
## Alternatives to Handle the Genesis File
Given the discussion on [#1286](https://github.com/cometbft/cometbft/issues/1286), here are some thoughts on how to change how we handle the genesis file.

In both cases, the `GenesisDoc` isn't in memory anymore; the GC will collect its only instance after exiting the `NewNode` function. 
**Note**: because we would be fetching the genesis file from disk, should we implement a sanity check to ensure it hasn't been tampered with after the `Node` was initialized? For example, we could verify the file's hash against the one stored in the state DB.

### Option 1: Store `GenesisDocProvider`
Store the `GenesisDocProvider` in the `Node` during initialization, rather than the genesis file's contents as we do now. As mentioned in [#1286](https://github.com/cometbft/cometbft/issues/1286#issuecomment-2353309745), the primary use of the genesis file post-initialization is for serving RPC APIs. Any other, less frequent, use can rely on the `GenesisDocProvider` to fetch the file from disk.

**Cons**: `GenesisDocProvider` not only retrieves the genesis file from disk but also [computes its hash](https://github.com/cometbft/cometbft/blob/30f527a964e3e324920c719acf612f9d0b1f66b4/node/setup.go#L80). Re-hashing the genesis file on every access introduces a performance overhead, which could degrade the responsiveness of the RPC APIs. However, this isn't a downside if we need the hash to do a sanity check as mentioned above. 

### Option 2: Use genesis file's path on disk
Since the `Node` always retains the genesis file's disk path, we could fetch the genesis file when needed leveraging the [`Config`](https://github.com/cometbft/cometbft/blob/30f527a964e3e324920c719acf612f9d0b1f66b4/node/node.go#L54). 

**Cons (?)**: this approach bypasses any additional operations performed by a custom `GenesisDocProvider` that users may define to process the `GenesisDoc` after it is read from the file.

**Comment by alesforz** [comment]
## Chunking
To serve the `genesis_chunked` endpoint, we store a [slice of 16MB chunks](https://github.com/cometbft/cometbft/blob/2c8d1e4909e9ee287428869fa233f631a95c4f67/node/node.go#L755) in memory. This results in **two copies of the `GenesisDoc` being held in memory**: one is the original `GenesisDoc`, and the other is the reassembled version from the split chunks. 

We could still use a simple cache to keep chunks in memory for a short time to serve the RPC requests.

### Option 1: Store the chunks in the file system
As proposed in [#1289](https://github.com/cometbft/cometbft/issues/1289), we could store the chunks on disk and fetch the appropriate chunk upon an RPC request.

**Cons**: This still results in two copies of the genesis file, but we shift the burden of the second copy from memory to disk.

### Option 2: Store the chunks' offsets 
As @jmalicevic points out [here](https://github.com/cometbft/cometbft/issues/1289#issuecomment-1700832253), we could store only the file offsets for each chunk, eliminating the need for additional storage.

**Cons**: Fetching a chunk would require an extra `seek` operation to move to the correct position in the file, slightly impacting performance. However, the potential storage savings are significant with genesis files that can be several GBs in size.

**Comment by jmalicevic** [comment]
Overall I think, we might have to keep it in memory for serving RPCs but do we have to keep two copies (chunked, and not chunked)? If the solution with pointers is not great, could we then keep only chunks and combine them when the RPC requests wants the whole file - or is that too expensive?

**Comment by andynog** [comment]
One solution is to implement logic that leverages the `Range` header, you can have the chunks on disk and if the range matches you return that or if not you do a file seek for a hybrid approach if needed. Remember that if you implement a custom way to serve chunks, the client has to implement logic to request the chunks the way the server expects.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Range

**Comment by alesforz** [comment]
> One solution is to implement logic that leverages the `Range` header, you can have the chunks on disk and if the range matches you return that or if not you do a file seek for a hybrid approach if needed. Remember that if you implement a custom way to serve chunks, the client has to implement logic to request the chunks the way the server expects.
> 
> https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Range

We can consider that for the current JSON-RPC APIs, but since HTTP headers aren't available with gRPC endpoints, we'll need to rethink how to serve chunks when we implement the gRPC GetGenesis endpoint.

**Comment by alesforz** [comment]
@jmalicevic @andynog 

A thought: why don't we just use gRPC streaming? gRPC supports both client-side and server-side streaming. This allows us to break the genesis file into smaller chunks and send them piece by piece. We wouldn't need to load the entire genesis file into memory at once. Additionally, the client doesn't need to make _N_ separate gRPC calls to retrieve _N_ chunks; instead, the entire transmission is handled within a single gRPC call.

The endpoint's code will look something like this:
```go
// GetGenesis streams the file content in chunks.
func (s *NetworkServiceServer) GetGenesis(/* params */) error {
    // e.g., 4MB chunk size	
    chunkSize = 1024 * 1024 * 4 

    file, err := os.Open(genesisFile)
    if err != nil {
        return err
    }
    defer file.Close()

    buffer := make([]byte, chunkSize)
    chunkNumber := 0
    for {
        // Read the file in chunks of size chunkSize
        n, err := file.Read(buffer)
        if err != nil {
            if errors.Is(err, io.EOF) {
	        break
            }
	    return err
        }

        // Stream the chunk back to the client 'stream' is a placeholder name. 
        // The streaming server to use here will be automatically generated
        // by make-proto. It'll be something like NetworkService_GetGenesisServer
        resp := Response {
            Content:     buffer[:n], 
	    ChunkNumber: int32(chunkNumber),
        }
        err = stream.Send(resp)
        if err != nil {
            return err
        }

        chunkNumber++
    }

    return nil
}
```

Pros:
- We don't need to store chunks on disk or in memory.
- We don't need to store the genesis in memory, just open the file and stream it.
- No need for the client to keep track of multiple gRPC calls to reassemble the genesis file

What do you think?

**Comment by alesforz** [comment]
> We can implement a streaming gRPC for that sure but we’d still need to support the endpoint in JSONRPC until it's deprecated

Our JSON-RPC implementation supports WebSocket connections, allowing us to stream the genesis file in a single RPC call. We would need to refactor the `/genesis` and `/genesis_chunked` APIs, though. These changes would be breaking, as clients currently need to make a separate RPC request for each chunk they want to download.

Alternatively, I propose keeping the JSON-RPC APIs as they are but implementing the 'store the offsets into the file' strategy under the hood.

For the gRPC endpoint, I would implement streaming from the outset.

**Comment by jmalicevic** [comment]
@alesforz I like your proposal. Maybe just name the endpoint with `Streaming` as part of the name. And then yes, we can keep the current APIs that we have to keep with an optimized implementation. If you think that the current `/genesis` api can be written in a streaming way without breaking anything, that would also be acceptable.

**Comment by alesforz** [comment]
@jmalicevic As you know, the `/genesis` endpoint [checks](https://github.com/cometbft/cometbft/blob/b7721ce580b0b2b50bede54b397f34475f1bd352/rpc/core/net.go#L107) if the genesis chunks slice length is greater than one. If it is, it returns an error pointing to the `/genesis_chunked` endpoint; otherwise, it returns the genesis file.

Converting the `/genesis` endpoint into a WebSocket that streams the file would be ideal but would break existing clients. Alternatively, instead of returning "please use `/genesis_chunked`" when the genesis file is too large, we could return "please use `/genesis_streamed`" directing clients to a new JSON-RPC endpoint that streams the genesis file over a WebSocket.

The proposed changes would be:
- `/genesis`: Returns the genesis file if it's small; otherwise, directs clients to the `/genesis_streamed` endpoint. If you're a client using this endpoint to retrieve your genesis file, it means the file is smaller than the chunking threshold; otherwise, you would be using `/genesis_chunked`. Therefore, this proposal wouldn't change the behavior of the `/genesis` endpoint for you, and you could continue using it without any disruption.
- `/genesis_chunked`: Continues using the "one chunk at a time" method but refactored internally to avoid storing data in memory.
- `/genesis_streamed`: A new endpoint that streams the genesis file over a WebSocket.

This approach allows existing clients to continue using `/genesis` and `/genesis_chunked` as they currently do, while encouraging new clients to adopt the `/genesis_streamed` endpoint. Existing clients might also transition to the new endpoint over time, as it offers a more efficient alternative to the less efficient `/genesis_chunked`.

One question is whether it's worthwhile to do this work if we plan to deprecate the JSON-RPC endpoints in the future. Maybe we should focus on improving the underlying implementation of `/genesis_chunked` and leave it at that. But I do think streaming is a QoS improvement for JSON-RPC APIs users.

**Comment by alesforz** [comment]
> ## Alternatives to Handle the Genesis File
> Given the discussion on [#1286](https://github.com/cometbft/cometbft/issues/1286), here are some thoughts on how to change how we handle the genesis file.
> 
> In both cases, the `GenesisDoc` isn't in memory anymore; the GC will collect its only instance after exiting the `NewNode` function. **Note**: because we would be fetching the genesis file from disk, should we implement a sanity check to ensure it hasn't been tampered with after the `Node` was initialized? For example, we could verify the file's hash against the one stored in the state DB.
> 
> ### Option 1: Store `GenesisDocProvider`
> Store the `GenesisDocProvider` in the `Node` during initialization, rather than the genesis file's contents as we do now. As mentioned in [#1286](https://github.com/cometbft/cometbft/issues/1286#issuecomment-2353309745), the primary use of the genesis file post-initialization is for serving RPC APIs. Any other, less frequent, use can rely on the `GenesisDocProvider` to fetch the file from disk.
> 
> **Cons**: `GenesisDocProvider` not only retrieves the genesis file from disk but also [computes its hash](https://github.com/cometbft/cometbft/blob/30f527a964e3e324920c719acf612f9d0b1f66b4/node/setup.go#L80). Re-hashing the genesis file on every access introduces a performance overhead, which could degrade the responsiveness of the RPC APIs. However, this isn't a downside if we need the hash to do a sanity check as mentioned above.
> 
> ### Option 2: Use genesis file's path on disk
> Since the `Node` always retains the genesis file's disk path, we could fetch the genesis file when needed leveraging the [`Config`](https://github.com/cometbft/cometbft/blob/30f527a964e3e324920c719acf612f9d0b1f66b4/node/node.go#L54).
> 
> **Cons (?)**: this approach bypasses any additional operations performed by a custom `GenesisDocProvider` that users may define to process the `GenesisDoc` after it is read from the file.

@jmalicevic @andynog Any comments on this? Anything you would do differently? Have I forgotten viable options?

**Comment by andynog** [comment]
Hi @alesforz I think this is good, concerning file chunks I expressed some ideas [here](https://github.com/cometbft/cometbft/issues/1289)

For the hashing, we should not do it every time we access the file, I thought this was only needed when the server starts and we need to save the hash in the db if we don't have one

**Comment by alesforz** [comment]
With the merging of #4349, we have completed all the work in this tracking issue 🥳

**Comment by alesforz** [comment]
With the merging of #4349, we have completed all the work in this tracking issue 🥳
