### ISSUE TITLE
Add support for fast prototyping

### ISSUE THREAD

**Issue by lasarojc** [cometbft/cometbft#1059]
## Target audience

Consensus developers

## Problem definition

The e2e testbed demands large amounts of resources to run medium/large scale experiments (16-128 nodes).
This comes from the fact that the testbed runs CometBFT in full on the testbed nodes.
Furthermore, there is no support for fast prototyping.
For instance, building a Docker image is slow, and the image is heavy (several GBs).

## Upside

Run small-scale experiments on a laptop / server-class machine will speed up prototyping and testing fixes and/or improvements.

## Downside

Requires mocking reactors.

The system will be a slimmed down version of what actually runs on the nodes (less reactors).
Hence, there is a small chance that improvements in this simplified environment do not translate into improvements in real-world setups.
This is an inherent (and standard) risk to such an approach.
To mitigate it, the developper needs to understand beforehand the impact of mocking one (or more) reactors.

```[tasklist]
## Original Goals
- [x] Speed-up docker image construction
- [x] Add new small docker image (new make target)
- [x] Include Prometheus server support to docker compose
- [ ] https://github.com/cometbft/cometbft/issues/1082
- [ ] https://github.com/cometbft/cometbft/issues/1083
- [ ] https://github.com/cometbft/cometbft/issues/1084
- [ ] https://github.com/cometbft/cometbft/issues/1085
```

```[tasklist]
## Integration Goals (provide PRs for the following)
- [ ] Faster Docker builds (possibly leveraging go's cross-compilation simplicity)
- [ ] Plugging custom reactors (+ the "demo" custom reactor for the mempool)
- [ ] Interactive reporting/visualization tool
```

```[tasklist]
## Stretch goals
- [ ] Add Kubernetes support to e2e [2w]
- [ ] Integrate the scripting into the e2e test.
```

## Definition of done
- The e2e testbed includes a fast-prototyping mode. 
In this mode, the docker image is tailored to its bare minimum, and building it (along with the generator and runner) is immediate.
- The fast-prototyping mode allows to mock a reactor, such as consensus. 
- There is a new custom benchmark.
This benchmark starts a Prometheus node which targets all the validators.
At the end of a run, the benchmark return aggregated (customizable) key metrics from the data collected in Prometheus.
```

**Comment by lasarojc** [comment]
The excellent work done in #1139 resulted in this [branch](https://github.com/cometbft/cometbft/tree/pierre/fast-prototyping-1059)

To drive this issue to a closure, it has been advised that we split split the code into different PRs targeting main, because the current branch aggregates multiple contributions and is built on top of #1043, which hasn't been merged and is on backlog.
A list of these PRs were added to the description.
