### ISSUE TITLE
Understand use cases blocked by high BW usage and what would take to unblock them

### ISSUE THREAD

**Issue by lasarojc** [cometbft/cometbft#1060]
## Target audience

Consensus developers

## Problem definition

High usage of bandwidth can prevent (or make difficult) the use of CometBFT in some cases.
For example, while vote extensions may be a useful abstraction for application developers, its costs in terms of added bandwidth and extra latency was considered prohibitive by at least one chain.

We need to identify blocked use cases, understand them, and determine what it takes in terms of bandwidth usage reduction to unblock them. 
While there may be many such use-cases, we need to time-box this effort and will focus here on uses of vote-extensions.

## Upsides 

- This effort will guide our work on bandwidth consumption reduction.
- The reduction will benefit all use-cases, not only the ones in which we focus.
- This work is highly parallelizable with others

## Downsides

- We depend on feedback from partners which may not be willing to quickly share information.

## Tasks

Time-boxed to 2 weeks.
```[tasklist]
- [x] Determine the list of partners to talk to.
- [x] Understand use cases and determine impact of VE in bw usage
- [x] Determine desired bw reduction.
```

## Definition of done

- A list of vote-extensions use-cases, with as much detail as needed to determine the bandwidth impact (e.g., average vote-extension size; impact on other messages, such as proposals) is provided.
- Have determined (hard) limits for the use case to be enabled.
