### ISSUE TITLE
ADR-101: Backport to `v0.38.x`

### ISSUE THREAD

**Issue by jmalicevic** [cometbft/cometbft#1419]
This issue covers all the tasks needed to backport the implementation of ADR-101 (#574) from main into v0.38.x.

We will backport this feature into an experimental branch because :
- We have to break existing go API interfaces (legacy gRPC, in particular) and v0.38.x is already released
- The pruning mechanism is happening in the background now, instead of synchronously between heights which changes the existing logic. 

The implementation will be backported step by step, porting one big feature at a time. 

- [x] Create a `v0.38.x-experimental` branch with all the protections of release branches. 
- [x]  #1421 
     commit: 65a88b9f8 
 This step will be the basis for backporting all other gRPC endpoints. 
- [x] #1422
     commits:  04dfaf57f, c710bb836 (metrics for pruning),  fe644d81e 
- [x] #1423 
       commits: 96f4ab8fd 
- [x] Backport gRPC endpoints:
     - [x]  BlockService backport to v0.38.x, commits: 84e2e01e6, 8006a7456 #1440
     - [x] BlockResultsService  backport to v0.38.x, commits: f9c17b45d #1440
     - [x] PruningService (Block) backport to v0.38.x,  commits: 69843bed0 #1471 
     - [x] #1481
     - [x] Close method for gRPC client 3479642e2 #1474 
- [x] #1478
- [x] Backport fixes and optimizations 
         commits: 6fc2c37c8 (depends on the gRPC endpoints so will be done at the end ): #1473
- [x] #1475
- [x]      #1480  
       Manual backport of #1467
- [x] #1491
- [x] #1503 
       e2e: Fix docker port aliasing - failing upgrading tests.(backport #1507)
- [x] #1536 
   e2e: Reduce test flakiness - backport #1492 

Backporting the pruning mechanisms is independent of the gRPC backports and can be done in parallel. The pruning service endpoints depend on the pruning mechanisms being implemented.
