### ISSUE TITLE
ADR-101: Backport to `v0.37.x`

### ISSUE THREAD

**Issue by jmalicevic** [cometbft/cometbft#1420]
This issue covers all the tasks needed to backport the implementation of ADR-101 from main into v0.38.x.

We will backport this feature into an experimental branch because :
- We have to break existing go API interfaces and v0.37.x is already released
- The pruning mechanism is happening in the background now, instead of synchronously between heights which changes the existing logic. 

The ADR will be backported step by step, porting one big feature at a time. 

- [ ] Create a `v0.37.x-experimental` branch with all the protections of release branches. 
- [x] Port BaseService and VersionService to v0.37.x (PR #818 ): #1438 
 This step will be the basis for backporting all other gRPC endpoints. 
- [ ] #1444   
       commits:  04dfaf57f, c710bb836 (metrics for pruning),  fe644d81e 
       commit 6fc2c37c8 depends on the gRPC endpoints so will be done at the end 
- [ ] Backport indexer pruning mechanism.
       commits: 96f4ab8fd 
- [ ] Backport gRPC endpoints:
     - [x]  BlockService backport to v0.37.x:  commits: 84e2e01e6, 8006a7456  #1441
     - [ ] #1442
        Not trivial, due to changes on ABCI interface.
     - [ ] PruningService (Block) backport to v0.37.x  commits: 69843bed0
     - [ ] Indexer pruning service  backport to v0.37.x commits: 4f0d5b4f0
     - [ ] Close method for gRPC client commits 3479642e2
- [ ] Metrics for indexer pruning service monitoring backport to v0.37.x 
       commits: 08cf31c67
- [ ] Backport fixes and optimizations 
         commits: 6fc2c37c8 (depends on the gRPC endpoints so will be done at the end ) 
- [ ] ADR-101 Backport documentation to v0.37.x 
       commits: 46a4cea42 

Backporting the pruning mechanisms is independent of the gRPC backports and can be done in parallel. The pruning service endpoints depend on the pruning mechanisms being implemented.

**Comment by cason** [comment]
We are temporarily stopping the efforts on this backport effort, in order to focus first on the backport of the same features to `v0.38.x-experimental` (#1419).

**Comment by adizere** [comment]
Closing. No clear signals that it's needed from users.
