### ISSUE TITLE
`cometbft-rs` changes

### ISSUE THREAD

**Issue by sergio-mena** [cometbft/cometbft#1834]
Modify `cometbft-rs` to support the new `cometbft` protobufs ~while keeping compatibility with legacy protobufs~.
The legacy releases are supported by `v1beta*` packages generated from versioned CometBFT protobufs.

* [x] Clone `tendermint-rs` into `cometbft-rs`
* [x] cometbft/cometbft-rs#5
* [x] cometbft/cometbft-rs#2
* [x] cometbft/cometbft-rs#9
* [x] Add v1.x support to `CompatMode` in rpc ~~to use version-prefixed request path~~ cometbft/cometbft-rs#12

**Comment by mzabaluev** [comment]
> while keeping compatibility with legacy protobufs

Do we really need the legacy module structure in `tendermint`? By the protobuf changes in CometBFT [ADR-103](https://github.com/cometbft/cometbft/pull/817), the side-by-side generated modules for 0.x are redundant to the versioned structure in `cometbft` protos as of v1.0.x. Since we're renaming the crates anyway, backward compatibility for the API is less of a concern: the users of new `cometbft-proto` porting from `tendermint-proto` have to change their imports anyway, so it's just a little more stretch to change to `cometbft::*::v1` imports or whatever older beta revisions they need to be on.

**Comment by sergio-mena** [comment]
Yeah, I had that thought when working on cometbft/cometbft-rs#2; but, out of caution I left them there (it's always easier to remove than to add back). Feel free to nuke them

**Comment by mzabaluev** [comment]
Regarding `CompatMode::V1` automatically adding `/v1` to request URL paths: this is not straight-forward between the HTTP client (where `/v1` should be added to the base URL as a suffix) and the WebSocket client (where the endpoint instantiated by the CometBFT node is typically, but not necessarily, something like `/v1/websocket`). In the Go client, the API user has to encode the version suffix into the URL explicitly as well, so I think we should follow this.

The only cosmetic change left is to rename `CompatMode::V0_37` to `V1` as was done at some point in #7.

**Comment by mzabaluev** [comment]
> The only cosmetic change left is to rename `CompatMode::V0_37` to `V1`

We've decided against this and with https://github.com/cometbft/cometbft-rs/pull/12, all is done.
