### ISSUE TITLE
Storage optimizations: Q1 2024 tracking issue

### ISSUE THREAD

**Issue by jmalicevic** [cometbft/cometbft#2058]
## Q1 storage optimizations plan

This issue serves as a meta-tracking issue, outlining a subset of items from #44 that will be done and covered in Q1 2024. 

In Q4 2023, we have implemented 2 database key representations that are different from what CometBFT is currently using, along with in-process compaction of the database. Compaction can be explicitly triggered to force the backing database to reduce the storage footprint. 

In Q1 we need to evaluate whether the new layout introduces overheads or it reduces the database access time and has any impact on the efficiency of pruning and compaction. 

At the end of Q1 we expect the following PRs to be merged:
- [x] https://github.com/cometbft/cometbft/pull/1974 
- [ ] #2327 (We are porting the changes in #1764 as an additional layout supported. #1814 is dropped) 
- [x] https://github.com/cometbft/cometbft-db/pull/111  and https://github.com/cometbft/cometbft/pull/1972
- [ ] A PR solving #2057 

Documentation updates:
- [ ] https://github.com/cometbft/cometbft/issues/2406
- [ ] A report on the findings will be included as part of #1044. 

- [ ] https://github.com/cometbft/cometbft/issues/1044 
We are running experiments using metrics in #1974 and DB specific metrics from [a branch in the cometbft-db repo](https://github.com/cometbft/cometbft-db/tree/jasmina/goleveldb-with-prom-histogram-metrics ). 
The DB metrics will not be merged as is because they introduce some overhead and should not be used in production.
