### ISSUE TITLE
v0.38: Adoption, debugging, support tracker

### ISSUE THREAD

**Issue by adizere** [cometbft/cometbft#2068]
## This issue tracks work related to adoption of v0.38

```[tasklist]
### Performance related
- [x] Berachain P2P-related debugging
- [ ] https://github.com/cometbft/cometbft/pull/2084
- [x] Osmosis & block sync -> Anton
- [ ] Injective & state sync -> Hernan
```

```[tasklist]
### General scope
- [ ] https://github.com/vocdoni/vocdoni-node/issues/1239
- [x] Babylon team "the proposer may be misbehaving; prevoting nil" -> Was SDK related
- [ ] https://github.com/cometbft/cometbft/issues/2126
```

```[tasklist]
### Security related
- [X] v0.38.3 release with security vulnerability fix
- [ ] https://github.com/cometbft/cometbft/issues/2109
```

**Comment by adizere** [comment]
most 0.38 "adoption" work is shifting towards technical front, specifically mempool working group & associated improvements, work captured mostly in #2803
