### ISSUE TITLE
v1 QA

### ISSUE THREAD

**Issue by melekes** [cometbft/cometbft#2100]
The focus of this QA process for releasing v1 is to:
- test regressions with respect to our baseline, the [v0.38 results](https://github.com/cometbft/cometbft/blob/dd9e699bdc7171cba9be2f187d21e11e4195ad61/docs/references/qa/CometBFT-QA-38.md) (see [#31](#31)),
- assess the performance of new features, including [PBTS](#1731) and [storage optimizations](#44),
- perform a stress test,
- optionally, test experimental features for bandwidth improvement.

The main goal of the QA process is to validate that there are no meaningful, substantial regression from the previous version. There is a regression if we see that there is a difference bigger than ~10% in the results.

## Preliminary QA

```[tasklist]
### Tasks
- [ ] https://github.com/cometbft/cometbft/issues/903
- [ ] https://github.com/cometbft/cometbft/issues/2058
- [ ] ~~stress test with high volumes of txs / big txs (aka "p2p storm")~~
- [ ] ~~update default parameters based on ^ (_plus other possible fixes tbd_) e.g. mempool parameters~~
- [x] Run preliminary test of PBTS branch on 200 nodes
- [ ] https://github.com/cometbft/cometbft/issues/2323
- [ ] https://github.com/cometbft/cometbft/issues/2460
```

### Hypotheses to verify

- [ ] **new key layout** helps access time and compaction
- [ ] **bandwidth optimizations** reduced the amount of data sent/received
- [ ] with **updated default parameters**, CometBFT is resilient against high volumes of txs / big txs.

### Questions

1. Do we want to make some bandwidth improvements non-experimental?

### Improve end-to-end test framework

- [X] https://github.com/cometbft/cometbft/issues/2066
- [X] https://github.com/cometbft/cometbft/issues/2094
- [X] https://github.com/cometbft/cometbft/issues/2148 
- [X] https://github.com/cometbft/cometbft/issues/2192 
- [x] https://github.com/cometbft/cometbft/issues/2328 

### New metrics

- [X] #1512
- [X] #1974 

## Final QA

Each task will update a section on the final QA report.
```[tasklist]
### Tasks
- [ ] ~~Capture metrics of v0.38 baseline (Optional, to do only if existing v0.38 metrics can't be reused)~~
- [ ] #2461
- [ ] #2513
- [ ] https://github.com/cometbft/cometbft/issues/2656
- [ ] https://github.com/cometbft/cometbft/issues/2657
- [ ] ~~Test storage on experiments longer than 90s~~
- [ ] https://github.com/cometbft/cometbft/issues/2746
- [x] Improve QA instructions as the tests are run #2405
```

**Comment by faddat** [comment]
Yeah I don't know if you have the papers and really if you go by the security issue on this repo, you will learn absolutely nothing about P2P storms I promise, so here are the papers:

https://docs.google.com/document/d/1oCjsVYMaV77etxOEbDxh58vkAQaXf7RAkhXvF_8GYis/edit?usp=drivesdk

https://docs.google.com/document/d/1q6C1xGdbFaTwJQkzevAHxFsqyUyL_vzJvunp5XESo60/edit?usp=drivesdk


https://docs.google.com/document/d/1HNSF75A2K8CgFIAagoF2b3MCbZ_BS-7v5l4b9romPW4/edit?usp=drivesdk

And I hope that I'm being sufficiently clear, what I'm trying to say here is that the security issue here is literally wrong and that I have disagreed with it for the entire time that it has been published and have repeatedly asked for my company's name to be removed from it.
