### ISSUE TITLE
`timeout` params [Tracking issue]

### ISSUE THREAD

**Issue by melekes** [cometbft/cometbft#2873]
### Summary

```
timeout_propose = "3s"
timeout_propose_delta = "500ms"
timeout_prevote = "1s"
timeout_prevote_delta = "500ms"
timeout_precommit = "1s"
timeout_precommit_delta = "500ms"
timeout_commit = "1s"

skip_timeout_commit = false
```

When speaking about `timeout` parameters, there are multiple concerns.

1. We don't need that many parameters
2. App developers want consistency across validators, even though params may vary depending on validator's network topology and runtime
3. App developers want a way to set block intervals (think of it as if all validators set the same `timeout_commit` value).

Note there are other potential ways to align parameters in a network https://github.com/cometbft/cometbft/issues/1617.

```[tasklist]
### Tasks
- [ ] Remove `skip_timeout_commit` in favor of setting `timeout_commit` to `0`
- [ ] Remove `timeout_prevote` `timeout_precommit` in favor of calculating them https://github.com/tendermint/tendermint/issues/2920#issuecomment-445874592
- [ ] Merge `timeout_propose_delta`, `timeout_prevote_delta`, `timeout_precommit_delta` into a single `round_delta`
- [ ] Make `timeout_commit` a consensus parameter
```

So (1) will be solved by 1,2,3. (3) - by 4. (2) - by social consensus & external tools https://github.com/cometbft/cometbft/issues/1617

To protect against greedy proposers, we will likely need to punish validators who propose a block those timestamp is less than `LastBlock.Time + TimeoutCommit + SomeDelta`.

**Comment by sergio-mena** [comment]
These are my thoughts:
* Task 1. Fully agree
* Task 2. Makes sense in principle, although the relations pointed out in [this comment](https://github.com/tendermint/tendermint/issues/2920#issuecomment-445874592) are _inequations_, so they don't really tell you the value of some params in terms of others, but rather bounds (i.e., min or max values). I recently heard @cason say something along these lines.
  * Something I do see clearly here is that I don't see any practical reason not to merge `timeout_prevote` and `timeout_precommit` into one single value. As the event these timeouts relate to are vote reception (same number, similar size)
* Task 3. Fully agree with `timeout_prevote_delta` and `timeout_precommit_delta` (both relating to votes). Not 100% sure about `timeout_propose_delta`, as it has to do with a proposal and its block, with can be way bigger in size than votes.
* Task 4. Fully agree

**Comment by melekes** [comment]
@josef-widder @milosevic how feasible it is to actually calculate values of `timeout_prevote` (1s) & `timeout_precommit` (1s) from the round delta (500ms) - https://github.com/tendermint/tendermint/issues/2920#issuecomment-445874592? As @sergio-mena pointed out they define "min" values. But this is exactly what we're looking for! "min" values, which if validators fail to agree in round 0, get increased in round 1.

**Comment by melekes** [comment]
cc @ebuchman ^

**Comment by cason** [comment]
See https://github.com/cometbft/cometbft/issues/2547

**Comment by cason** [comment]
> Something I do see clearly here is that I don't see any practical reason not to merge timeout_prevote and timeout_precommit into one single value. As the events these timeouts relate to are vote reception (same number, similar size)

They don't have similar sizes when we have vote extensions......

**Comment by cason** [comment]
So, jumping here later.

Timeouts should be based on the size of the messages they refer to.

`timeout_propose` is strictly dependent on the typical block size, it should be computed based on the maximum block size in a network. `timeout_propose_delta` is the correction for this value, when underestimated. This should also depend on the block size.

`timeout_prevote` is more an optimization than anything. It defines how much time we still wait, when failing to observe a 2/3+ quorum for the same value, for additional votes that might change our action (we may see a 2/3+ quorum if we wait a little longer). There is some important discussion regarding the removal of this timestamp, or at least ignoring it when we realize we can't get a 2/3+ quorum at all from the already received messages (typical case: 2/3+ prevotes for nil).

`timeout_precommit` is really relevant for liveness. It is not an optimization. Once we reach GST, i.e., the system respects the current timeouts, we need all correct validators to see a 2/3+ quorum of precommits in the case one correct validator has seen it. Without this, the system might incur in the hidden lock issue, which prevents progress.

Before vote extensions, there was no reason to consider that prevotes and precommits would have distinct latencies, as both are fixed-size messages. This changes with vote extensions.

**Comment by melekes** [comment]
- [ ] revert and deprecate https://github.com/cometbft/cometbft/pull/2926 in v1
- [ ] deprecate `timeout_commit` on main
