### ISSUE TITLE
docs: An initial overhaul targeted for v1 release

### ISSUE THREAD

**Issue by thanethomson** [cometbft/cometbft#302]
We need to overhaul our documentation, down to the information architecture level. Consider this a long-running tracking issue for a pretty big sub-project, potentially spanning across quarters.

Ultimately what we want is documentation that is **user-centric**, is **useful** and ultimately **delightful** to our users, and the Tendermint Core documentation has, up to now, been very sparse and occasionally cryptic.

To that end, my recommendation is first to break down the documentation by **user type** to allow folks easy entrypoints into the documentation. Each of the types of users we're targeting are as follows:
1. Application developers - i.e. ABCI developers
2. Operators - people who run validators, full nodes, seed nodes, etc.
3. Integrators - folks who integrate with our APIs/publicly exposed surfaces, like our RPC
4. Consensus engine developers - folks who have traditionally forked the consensus engine and tweaked it to their needs, or who have used our code as a library and depend on our Go APIs

There may be an additional type of "user" here that we haven't yet considered in-depth: **researchers/academics**.

Next, we should break each user type's documentation into 4 dimensions (where relevant, of course), inspired by the [Diátaxis framework](https://diataxis.fr/):
1. Tutorials
2. How-to guides
3. Explanation
4. Reference

If there's a better framework/approach, by all means please suggest it.

cc @adizere @alijnmerchant21 

---

### Definition of done

This issue can be closed when we're confident that we've at least structured our documentation well according to this framework, and is relevant to the releases we've made publicly available.

Follow-up work can include the addition of new tutorials, how-to guides, etc. as the system evolves, but that can be tracked in separate issues.

---

### Sub-tasks

Please add sub-tasks here as you see fit, and feel free to reach out to team members and users to help populate this.

#### Docs folder
   

- [x] #1613

- [ ] Tutorials
   - [ ] Identify which types of tutorials would be most valuable for app developers
- [ ] How-to guides
   - [ ] Identify which types of how-to guides would be most valuable for operators
- [ ] Reference
   - [ ] #392

**Comment by alijnmerchant21** [comment]
Thank you @thanethomson for putting this together. Here are my 2 cents on this:


1. We should make the best of the existing documentation that we have with Tendermint. So, whatever is good and can be reused should be reused. 
2. The tutorial and how-to guide should be paired with articles. These articles should go in-depth for the respective topics mentioned in the tutorial/guide. 
3. Since we have clearly defined our users, (and they are a relatively small subset), we should gather feedback from them on what they would like to see in the document. I think of it as a collective resource maintained collectively.

**Comment by lasarojc** [comment]
Some suggestions for a quick reorg, in line with @alijnmerchant21's comment, which should already help a bit.
* Intro, What is CometBFT -> (move to)  Intro.
* Intro, Install CometBFT -> Guides, Install Guide
* Intro, Upgrading from TM -> Guides, Upgrading from TM
* Intro, Quick Start -> Guides, Quick Start Guide
* Apps, * -> Guides

**Comment by adizere** [comment]
One particular problem I keep on encountering with users (operators) is explaining to them how to enable debug logging. We're currently providing (with @cason today in a chat with NowNodes RPC providers) this info:

```toml
# https://docs.cometbft.com/v0.34/core/how-to-read-logs
log_level = "main:info,state:info,statesync:info,*:error"
# From https://docs.cometbft.com/v0.34/core/configuration 
# https://docs.cometbft.com/v0.37/core/running-in-production#logging 
```

Which is not ideal, but in particular the [last link](https://docs.cometbft.com/v0.37/core/running-in-production#logging) seems to serve well!

Two observations:
- Most of the time, when I reference people to our docs, it's for debugging purposes. 
- Most of the time, it is operators that I reference to our docs. It's possible the other classes of users often look directly in the code
    - Have not encountered a need to give to application developers/Integrators/consensus engine developers a link to our docs yet.

**Comment by lasarojc** [comment]
> Some suggestions for a quick reorg, in line with @alijnmerchant21's comment, which should already help a bit.
> 
> * Intro, What is CometBFT -> (move to)  Intro.
> * Intro, Install CometBFT -> Guides, Install Guide
> * Intro, Upgrading from TM -> Guides, Upgrading from TM
> * Intro, Quick Start -> Guides, Quick Start Guide
> * Apps, * -> Guides

These changes are in pr #492

**Comment by cason** [comment]
Adding up to Adi's comment above, some users reported not being able to setup a higher log level to a single module, that is why some times we have to handle with gigantic logs with all logs in debug level. I was about to create an issue to:

- Check if increasing the log level for a single or some modules indeed works in all supported versions
- Check it the documentation, for all supported version, is correct, in particular the list of module names (https://docs.cometbft.com/v0.34/core/how-to-read-logs)
- Put in evidence and centralize instructions of how to increase the log level of a specific module, so we can provide a single link to users when asking for additional debug information

**Comment by alijnmerchant21** [comment]
Based on comments above, I have a feeling that we should have a dedicated section for 'logs.' This would be done taking inputs from operators and other heavy log users.

**Comment by adizere** [comment]
# CometBFT documentation requirements for v1

- [CometBFT documentation requirements for v1](#cometbft-documentation-requirements-for-v1)
  - [High level goals](#high-level-goals)
  - [Needs per user class](#needs-per-user-class)
    - [Application developers](#application-developers)
    - [Operators](#operators)
    - [Core developers](#core-developers)
  - [Out of scope](#out-of-scope)

## High level goals

Consolidation of all documentation into a unified place. Specifically:

- Ensure that we fill any important gaps we have in the docs -> add content.
- Move existing content from other places (specs, wiki, etc.) to a unified place
  and make it easier to navigate -> move content.
- Persona-based design: Start from what different users need -> re-organize
  content.

## Needs per user class

There are specific needs per user class.

### Application developers

They need as follows:

- Tutorials
    - The user is studying: trying to learn how to develop a built-in app
    - Or how to create an external app
    - <docs.cometbft.com>
- How-to
    - Support in the performing of a specific task
    - Useful for Cosmos SDK developers
    - Upgrade from Tendermint v0.34 to CometBFT v0.34
    - Upgrade from v0.38 to v1
    - <docs.cometbft.com>
    - UPGRADING.MD and CHANGELOG.MD
- Explanation (users study something)
    - Useful for Cosmos SDK developers
    - ABCI++ vs. ABCI
    - Upgrades Taxonomy
    - Support policy for CometBFT
- References (users apply their knowledge)
    - Useful for Cosmos SDK developers
    - ABCI++ spec
    - Semantic versioning

### Operators

They need:

- Tutorials
    - How to read logs
    - How to start new networks, basic node operations
- How-to
    - Debug or change log levels
    - Change various configuration (config.toml) parameters
- Explanation
    - What is the Data Companion API
    - Running in production (?)
    - Node types [terminology](https://github.com/cometbft/cometbft/wiki/Node-Types)
- References
    - How to change/optimize their nodes: p2p, storage, bandwidth
    - How to use/optimize the Data Companion API

### Core developers

Includes many of the needs of "Application developers".

- Explanation
    - Comparison of Tendermint consensus algorithm with other consensus variants
    - Consensus algorithm & specs
    - ABCI++ specs
    - ABCI++ vs. ABCI

## Out of scope

The following is out of scope for the present issue.

Audience: External builder / investor / new teams considering their choices.

Goals with this:

- Ensure visibility into the *new* things that CometBFT v1 provides
    - Audience = interchain developers
- Ensure clarity over the current state of CometBFT
    - Ensure clarity that it is being actively developed -> link to roadmap,
      github project, etc, this will likely go on <cometbft.com> which needs to
      be revamped to be more product-focused.

These are non-interchain builders, developers, or investors who are looking to
learn more about CometBFT and interchain technologies.

- Tutorials
    - Presentations & Workshops
- Explanations
    - News
        - What's new in v1 (then v2, v3, etc)
            - ABCI++ Unlocks This (new use cases enabled)
        - Roadmap
            - Link to the public ICF roadmap for 2024 and project board
        - Github repository link
    - Consensus algorithm & specs
        - Comparison with other consensus algorithms
    - System attributes:
        - Performance: throughput and latency
        - Responsiveness
        - Reliability
        - Number and type of production use-cases: Who is using CometBFT?
    - CometBFT in the context of interchain technologies
        - Relation to Cosmos-SDK based apps & IBC

**Comment by adizere** [comment]
Should we consider this closed by #2105 ? Seems so given the DoD we wrote above

> Definition of done
This issue can be closed when we're confident that we've at least structured our documentation well according to this framework, and is relevant to the releases we've made publicly available.

If so, please feel free to close @andynog . If not, let's clarify the DoD for this issue.

**Comment by andynog** [comment]
@adizere, In my opinion we can consider this done as per #2105. We are not adding additional content at this time but we should keep in mind the [content of this list](https://github.com/cometbft/cometbft/issues/302#issuecomment-1784159659), there's valuable information there.

**Comment by adizere** [comment]
cool! closed by #2105
