### ISSUE TITLE
Don't re-use the internal message queue in block proposal

### ISSUE THREAD

**Issue by ValarDragon** [cometbft/cometbft#3130]
### Summary

Currently when you propose a block, you build and chunk up the proposal block, and sign it. Then we put our "Proposal" message onto the internal message queue, and then add every block part into the proposal queue.

https://github.com/cometbft/cometbft/blob/main/internal/consensus/state.go#L1250-L1261

This causes us to suffer the following latencies:
- We have to process everything ahead of the proposal & blockpart in the queue. Which could be very many peer votes gathered during proposal creation process.
- We have to go through extra validation logic (unlikely to be the bottleneck short term)

### Problem Definition

This + #3007 is likely contributing lots of delay to our block gossip times from the block proposer.

### Proposal

Instead of sending these messages onto the internal message queue's, lets handle writing the proposal data + block parts to WAL here (doing all the encoding in parallel, which is >75% of WAL write time), and then run the internal methods directly.

**Comment by ValarDragon** [comment]
After looking at the logic more carefully in #3136, I think what we should do is:

On Propose:
- Run the SetProposal method immediately
- Add all block parts immediately
- Make a new message on the internal message queue for "handleCompleteProposal" (which will take us into prevote).

We want to skip the delay for adding all block parts for gossip routines, but we want to unblock gossiping block data before doing our prevote.

I suggest the following implementation strategy:
- [ ] PR #1: Run SetProposal immediately
- [ ] PR #2: Make a new message for "handleCompleteProposal". Do each "addProposalBlockPart" and then put this new message into the internal message queue.
- [ ] PR #3: Replace add proposal block part with more efficient methods when its coming from us.

The over-arching claim is that after we sign a proposal, getting ourselves ready to gossip all block parts _should_ be instant, but right now its very much not, so we need to move to that :)

**Comment by cason** [comment]
> After looking at the logic more carefully in #3136, I think what we should do is:
> 
> On Propose:
> 
>     * Run the SetProposal method immediately
> 
>     * Add all block parts immediately
> 
>     * Make a new message on the internal message queue for "handleCompleteProposal" (which will take us into prevote).
> 
> 
> We want to skip the delay for adding all block parts for gossip routines, but we want to unblock gossiping block data before doing our prevote.
> 
> I suggest the following implementation strategy:
> 
>     * [ ]  PR 1: Run SetProposal immediately
> 
>     * [ ]  PR 2: Make a new message for "handleCompleteProposal". Do each "addProposalBlockPart" and then put this new message into the internal message queue.
> 
>     * [ ]  PR 3: Replace add proposal block part with more efficient methods when its coming from us.
> 
> 
> The over-arching claim is that after we sign a proposal, getting ourselves ready to gossip all block parts _should_ be instant, but right now its very much not, so we need to move to that :)

This is a good solution. Some comments.

- Run `SetProposal` and panic in case of error.
- Regarding PR2, we don't need that. We check if the proposal block is complete in `handleMsg`, this can be done inside `addProposalBlockPart`. Actually, it could also be done inside `SetProposal`.
- Regarding PR3: we probably need a method to set a full block. This method, in particular, could be use if (when?) we decide to remove block parts from the consensus logic. Namely, consensus sees a full block, someone else plays the role of putting parts together.

In fact, and this can be discussed more thoroughly, we may only need to:

1.  Call `SetProposal()` and `addProposalBlockPart` from the proposing routine. This has no real performance benefits, as ideally this should be done in parallel.
2. Create a `SetProposalBlock()` method, or something like that, invoked by `addProposalBlockPart` and also public, which would render testing much simpler in a lot of situations. This allows removing the logic on `handleMsg` regarding proposal block parts. Not to mention that ugly lock/unlock sequence.
