### ISSUE TITLE
Final review, testing, and merge of branch `feature/adr075-backport` into `main`

### ISSUE THREAD

**Issue by sergio-mena** [cometbft/cometbft#32]
Tasks:

- [ ] Ask the submitter of tendermint/tendermint#9857 to resubmit to Comet (if it's still private, let's do it ourselves)
- [ ] Final high-level review of tendermint/tendermint#9857 (all this code has already been reviewed twice)
- [ ] Run UTs, e2e locally
- [ ] (Optional) Run a testnet to make sure no major breakage is introduced
- [ ] Merge tendermint/tendermint#9857 into `main`
- [ ] Update documentation, such as state of ADR (if needed), update references to the backport feature branch

DoD:

- Branch `feature/adr075-backport` is merged
- No major breakages, any minor issue is solved
- Documentation up to date

Original Issue: tendermint/tendermint#9949

**Comment by yihuang** [comment]
Do you think it's good to resubmit the PR now?

cc: @mmsqe

**Comment by thanethomson** [comment]
We're considering implementing this as part of our standalone RPC companion. See #592.
