### ISSUE TITLE
chore: preparation for first release candidate `v1.0.0-rc1`

### ISSUE THREAD

**Issue by andynog** [cometbft/cometbft#3255]
Changes in preparation for our first release candidate (`RC1`) of `v1.0.0`:

### Tasks:
 - [x] files and documentation
   - [x] #3189
   - [x] #3300 (backport to `v1.x`)
   - [x] #3384
 - [x] api module
   - [x] tag (completed [here](https://github.com/cometbft/cometbft/releases/tag/api%2Fv1.0.0-rc.1))
   - [x] update go.mod #3192 
       - [x] #3231 (backport to `v1.x`)
 - [x] e2e Nighty passes OK
   - [x] #3234
   - [x] https://github.com/cometbft/cometbft/pull/3254
   - [x] https://github.com/cometbft/cometbft/pull/3262 
     - [x] #3294 (backport to `v1.x`)
   - [x] e2e nightly runs OK on `v1.x` branch (copy ci run link here once it's successful) 
     - [x] #3335 (need to revert PR so test on `main` nightly can pass)
     - [x] #3336
     - [x] #3362
     - [X] Successful e2e-nigthly-v1.x 
       - [X] https://github.com/cometbft/cometbft/actions/runs/9737093372
 - [x]  Changelog
   - [x] #3252
   - [x] https://github.com/cometbft/cometbft/pull/3253 (ready for review)
  - [x] Version update
    - [x] #3365
   - [x] Buf
     -  [x] Publish new protos to Buf before `v1.0.0-rc1` release 
       - https://buf.build/cometbft/cometbft/commits/commit/fedbb9acfd2f494b9755949cbb41dfca 
   
### v1.0.0 RC1 Release

Once all PRs and steps completed above:

 - [x] tag `v1.0.0-rc.1` and release
   - https://github.com/cometbft/cometbft/releases/tag/v1.0.0-rc1

### TODO after release:

  - [x] Comms (announcements)
  - [x] #3388

#### PR checklist

- [x] Tests written/updated
- [x] Changelog entry added in `.changelog` (we use [unclog](https://github.com/informalsystems/unclog) to manage our changelog)
- [X] Updated relevant documentation (`docs/` or `spec/`) and code comments
- [X] Title follows the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) spec

**Comment by andynog** [comment]
Just the nightly tests need to be fixed and pass

**Comment by adizere** [comment]
Great work Andy!
 
Shall we close this issue? Seems like it's done, except for the "comms" check box. We'll likely write an async update to share on all channels (Slack, X, Telegram).

**Comment by andynog** [comment]
Yes, it's done ! The comms will happen async. Thanks all for the contributions that made `v1.0.0-rc1` release possible ! 👍
