### ISSUE TITLE
DOG gossip protocol [tracking issue]

### ISSUE THREAD

**Issue by sergio-mena** [cometbft/cometbft#3297]
### Summary

This tracking issue monitors progress on the specification, implementation, and documentation of the Dynamic Optimal Graph (DOG) gossip protocol, first described in #3263 with preliminary performance measurements at scale. A prototype implementation already exists.

### Execution Steps

These are the tasks that we will need complete

#### Preliminary steps

- [X] Decide where to move the information in #3263, and the one in the Google Doc (likely: ADR & Spec)
- [x] #4318
  - [12 days]
- [x] #4319
  - [5 days]

Total: 17 days

#### Implementation

- [x] Create feature branch `feature/dog` [0 days]
- [X] Remove map with duplicate transactions (unbounded). We should be using the cache only [1 day]
- [x] Merge from `main` to have #3296 and #3303; fix conflicts [1 day]
- [X] How necessary are _nonces_ to the algorithm  [2 days]
  - Make decision: nonces were a solution for the base protocol; with redundancy control they are not necessary.
- [x] Clean up synchronization mechanisms, unify? [2 days]
- [x] #4543
  - Decide which parameters will be hard-coded and which will appear in `config.toml` [5 days]
  - Find optimal values to the algorithm's config [5 days]
    - Run tests at different scales
    - DoD: Obtain graphs/plots that justify the choice of params
  - Decide which messages will be part of the final algorithm [0 days, computed with previous task]
    - _NeedMoreRoutes_ (smoother than _Reset_), is it needed?
    - Do we need to send _Reset_ to _all_ nodes when losing a peer?
- [x] #4320
  - Design and implement the set of tests (together with acceptable KPIs) that the final algorithm should be passing [10 days]
  - Tests should include typical scenarios (perturbations) and known possible attacks (same tx to multiple nodes)
  - Timeboxed (risk of rabbit hole)
- [x] #4544
- [x] #4545
- [x] #4614
- [x] #4558
  - Post the remaining code in one or more PRs and get them merged [3 days]

Total: 24 days

#### Performance Measurements

- [x] #4430
- [x] #4481
- [x] #4347
- [x] #4606
  - Gather metrics at scale when code-complete [2 days]

Total: 7 days

#### Final steps

- [X] Finalise current Quint model for base algorithm [5 days]
  - Consider adding it as a section of the overall spec.
  - Formal spec of the Redundancy Control mechanism depends on time constraints, which Quint does not fully support.
  - In #4318, Quint was used in code snippets of the English spec from which Quint files were generated.
- [x] Revisit the existing mempool spec (by @hvanz and @otrack): is DOG incompatible in any way? Do we need to work on the spec? [2 days]
  - The specs in `specs/mempool/mempool.md` and `specs/mempool/quint/` are written at a higher level of abstraction and barely mention gossiping. There's no need to update them.
- [x] ~~Merge `feature/dog` back into `main` when the implementation is validated (200 node run, without report) [2 days]~~

Total: 9 days

**Comment by cason** [comment]
How this issues relates to https://github.com/cometbft/cometbft/issues/2803?

**Comment by sergio-mena** [comment]
@cason They are two different tracking issues
