### ISSUE TITLE
Improve experience for integrators

### ISSUE THREAD

**Issue by sergio-mena** [cometbft/cometbft#40]
High-level tracking issue for improvements targeting users who want to integrate with CometBFT-based nodes. This issue will be expanded over time.

Integrators currently make use of several surfaces/APIs of a CometBFT-based node in order to provide value-added services on top of those nodes. We want to provide ways to make integrators' lives easier.

This issue does _not_ cover the Go APIs. For improvements targeting the Go APIs, please see #42 

## Sub-issues:

* [ ]  Make consuming our Protobuf definitions easier
  * [ ] Restructure Protobuf usage in Tendermint: https://github.com/tendermint/tendermint/issues/9197#issuecomment-1332956463
  * [ ]  #95 
  * [ ] Publish our Protobuf definitions to the [Buf Schema Registry](https://docs.buf.build/bsr/introduction)
* [ ]  Provide better quality, standards-compliant APIs
  * [ ]  #81 
  * [ ]  tendermint/tendermint#7157
  * [ ]  #32
  * [ ]  #476 
  * [x] #75 
* [ ]  Allow for reliable offloading of data to companion services (e.g. independently scalable RPC services)
  * [x]  Decide which approach is best between:
     * #73 
     * #82 :heavy_check_mark: 
     * ABCI "shim" mechanism to intercept data between the node and ABCI app, as proposed by @lasarojc 
  * [x] #574 

Original issue tendermint/tendermint#9883
