### ISSUE TITLE
modularity: Rolling out new functionality faster, but reliably

### ISSUE THREAD

**Issue by lasarojc** [cometbft/cometbft#42]
High-level, multi-quarter tracking issue for specific work aiming to make the codebase more malleable, while maintaining high standards in terms of QA. This issue will be expanded over time.

The ecosystem benefits from changes to Tendermint Core/CometBFT relatively slowly. This is partially due to the sheer complexity and entanglement of various parts of the codebase as it has evolved somewhat organically over the years.

- [ ]  Having clear specifications will allow us to modularize the system better, which we believe will allow us to make changes more easily:
  - [ ] #23 
- [ ] #394
- [ ]  Improving our QA will give us greater confidence when making changes
  - [ ] #51
  - [x] #56
  - [ ] #834
  - [ ]  Add CI workflows to give better assurances with every pull request    
    - [ ]  Automatically flag Go API-breaking changes on release branches
    - [ ]  tendermint/tendermint#8003
    - [x] tendermint/tendermint#9872
- [ ]  Better testing for user-facing parts of the system  
  - [ ]  Ensure that all breaking RPC changes are deliberate
- [ ]  Automation and streamlining of upgrade processes
  - [ ]  https://github.com/cometbft/cometbft/issues/122
  - [ ]  Add automated upgrade tests to our QA for new major releases
- [ ] Versioning certain API surfaces will allow us to more easily roll out breaking changes
  - [x] #75 
- [x] #607 
- [ ] cometbft/tools-infra#1 

### Paying off technical debt

Paying off technical debt will enable us to move faster.

```[tasklist]
### RPC
- [ ] cometbft/cometbft#447
```

```[tasklist]
### Consensus internal refactoring
- [ ] #2663 
- [ ] #2659 
```

```[tasklist]
### Persona: Consensus engine developers
- [ ] Ideal Go API boundaries for consensus engine developers
- [ ] https://github.com/cometbft/cometbft/issues/342
- [ ] https://github.com/cometbft/cometbft/issues/2424
- [ ] https://github.com/cometbft/cometbft/issues/3383
```

These used to be tracked by cometbft/cometbft#43. Consolidated those issues here:

### Related:
* Offloading non-critical data will allow us to simplify the node architecture
  * https://github.com/tendermint/tendermint/pull/9437

Originally tendermint/tendermint#9882
