### ISSUE TITLE
v1.0.0 release plan

### ISSUE THREAD

**Issue by thanethomson** [cometbft/cometbft#578]
Let's capture our plans relating to the v1 release, ideally including dependencies and the critical path, in this tracking issue.

- [x] Revisit version number conversation: decide whether this should be v0.39.0 or v1.0.0 (see #357)
  - A decision was taken to cut this as v1
- [x] #1330
- [x] #75 
- [x] #1484 
- [x] #785 
- [x] Reach a decision on support policy #590 to be able to specify upfront the support policy for v1
- [x] #1731
- [x] #2543 
- [x] Tag `api/v1.0.0-alpha.1` just prior to tagging `v1.0.0-alpha.1`
- [x] @adizere last /internal packages checks before we cut the RC
    - [X] #2897 
    - [X] #3004 
- [x] #2610 

### For Release Candidate

  - [x] https://github.com/cometbft/cometbft/issues/2100
  - [x] #2580

  #### For `RC1` release (`v1.0.0-rc1`)

  - [x] #3190
  - [x] #3191
  - [x] #3189

  #### For `RC2` release (`v1.0.0.-rc2`)

- [x] #4454 
- [x] #4455 
- [x] #4456

#### For `major` release (`v1.0.0`) (not necessarily for alpha/RC)

- [x] https://github.com/cometbft/cometbft/issues/302
- [x] #2689
- [x] #2351
- [x] Consider adding a `readme.md` in the [`api`](https://github.com/cometbft/cometbft/tree/main/api) module in v1
- [x] #2710
- [x] #3416
- [x] #3834 
- [x] #4246
- [x] #4666 
- [x] #4656

```[tasklist]
### Tasks
- [X] Mark PebbleDB as the default backend (https://github.com/cometbft/cometbft/pull/4122)
```

**Comment by Altino1** [comment]
Os maus mesmo por meu dinheiro é so merda!!

**Comment by faddat** [comment]
What are the concerns that people have noted about the upgrade?

**Comment by andynog** [comment]
All tasks completed. 

CometBFT v1.0.0 [released](https://github.com/cometbft/cometbft/releases/tag/v1.0.0) 🚀
