### ISSUE TITLE
Update the e2e runner to disconnect a node from network in Digital Ocean testnet

### ISSUE THREAD

**Issue by sergio-mena** [cometbft/cometbft#58]
Tasks:

- [x] Familiarize with tendermint/tendermint#9860
- [x]  Clone it to Comet (merge to `main`)
- [x] Drive tendermint/tendermint#9860 to completion, including any non-CI testing needed
  - [x] #852
- [x] Test on DO
  - [x] cometbft/qa-infra#17

DoD:

* Patch finalized, reviewed, approved, and merged

Original issue: tendermint/tendermint#9950
