### ISSUE TITLE
spec/p2p: Define a structure for the P2P specification

### ISSUE THREAD

**Issue by cason** [cometbft/cometbft#598]
The high-level specification of the P2P layer adopted by CometBFT should be available under [`spec/p2p`](https://github.com/cometbft/cometbft/tree/main/spec/p2p).

This directory, however, is not empty, and includes content produced at different times and with distinct approaches. 

The goal of this issue is to:
1. Identify, evaluate and classify the existing content
2. Identify important components and execution flows to be documented
3. Propose a new structure for the P2P specification, combining the existing content and contend to be produced

## Current content

The P2P specification directory currently contains:

- [`messages/`](https://github.com/cometbft/cometbft/tree/main/spec/p2p/messages): documents the message types adopted by the six standard reactors (block sync, consensus, evidence, mempool, PEX, and state sync). Includes also the channel IDs each of the reactors is responsible for.
   - This content needs to be reviewed, in some cases updated (e.g., PEX-reactor messages refer to retracted v0.35 release)
- [`v0.34/`](https://github.com/cometbft/cometbft/tree/main/spec/p2p/v0.34): https://github.com/tendermint/tendermint/pull/9348. First attempt to fully document the implementation of the P2P layer in Tendermint Core. Despite referring to the v0.34.* releases, still applies to the current version.
   - Content to be reorganized for better readability. Currently is overly implementation-specific.
- `config.md`, `connection.md`,` node.md`, `peer.md`: short summary of main components of the P2P layer, produced in late 2019 (https://github.com/tendermint/spec/pull/53). 
   - Relevant source of information, although partially outdated. Complementary to the content of `v0.34/`directory.

## Definition of Done

- [x] Overview of the `p2p` package types and interfaces  (implementation-specific)
- [x] Overview of main components of the P2P layer (abstract level)
- [x] Table of contents for the P2P specification

**Comment by cason** [comment]
Part of the original content of this directory is going to be moved to a `legacy-docs` sub-directory. Handling this content is now tracked by a new issue: https://github.com/cometbft/cometbft/issues/981

**Comment by cason** [comment]
> * [ ]  I guess we should also consider [spec/p2p/reactor-survey.md](https://github.com/cometbft/cometbft/pull/80/files#diff-ba2f0f80844a5df01a58e9724d3570ea2b76eca13fdc641a4bf16504e280b040) from [WIP Spec: Draft for top-level p2p spec #80](https://github.com/cometbft/cometbft/pull/80) as "existing content" and make it part of the p2p spec as a requirement document.

This documentation was included in the knowledge base repository: https://github.com/cometbft/knowledge-base/pull/12/commits/880b60ad2f3a580eb53e9999e2b0aade12224d68

The mempool document is already there in a much more advanced shape.
