### ISSUE TITLE
Parsing big integers - tracking issue 

### ISSUE THREAD

**Issue by jmalicevic** [cometbft/cometbft#770]
This is a tracking issue for parsing big integers properly within the pubsub query and the indexer code. 

Currently we have a few places where we either handle big ints by parsing them as floats, or we do not handle them at all.

This issue spans accrross different CometBFT versions.

- [x] #726  - relates to v0.37.x and earlier versions
- [x] #769  - relates to main and v0.38.x
- [x] #767 - relevant for all CometBFT versions (including main). 
       For main and v0.37.x, it depends on resolving the previously listed issues first.

**Comment by sergio-mena** [comment]
Should we mark this as a bug?

**Comment by jmalicevic** [comment]
Yes, all the sub-issues are bugs, forgot to mark this one.
