### ISSUE TITLE
Implement ADR-102 PoC targeting main 

### ISSUE THREAD

**Issue by andynog** [cometbft/cometbft#825]
The initial Proof of Concept (PoC) for the standalone RPC implementation is hosted on a separate [repository](https://github.com/cometbft/rpc-companion)

This issue is a tracking issue for the implementation of the PoC. The following will have to be implemented to have a workable PoC:

- Ingest service
  - [ ] [Implement the RPC Ingest service](https://github.com/cometbft/rpc-companion/issues/1)
- Database
  - [ ] [Implement the Database Schema](https://github.com/cometbft/rpc-companion/issues/2)
- RPC service
  - [ ] [Implement the RPC service](https://github.com/cometbft/rpc-companion/issues/3)

**Comment by andynog** [comment]
Closing this in favor of #707 tracking issue. Duplicate.
