### ISSUE TITLE
Rename to cometbft

### ISSUE THREAD

**Issue by thanethomson** [cometbft/cometbft#93]
Tracking issue to rename our fork of Tendermint Core to "CometBFT".

The following needs to be done on all major branches (`v0.34.x`, `v0.37.x`, `main`), so we should submit PRs to main and backport where possible. The dependency updates probably won't be able to be automatically backported.

- [x] cometbft/cometbft-db#7
   - [x] #132
- [x] Rename package in `go.mod`
   - [x] #126
- [x] #128
- [x] #100
- [x] Migrate changelogs to use unclog
    - [x] #105
    - [x] cometbft/cometbft-db#12
- [x] #211
- [x] #225
- [x] #167
- [x] Update documentation
     - [x] #124
     - [x] #178
     - [x] #127
     - [x] #120
     - [x] #187
     - [x] #249 
     - [x] #168
     - [x] #319 
     - [x] #391 
- [x] Update the test infrastructure
    - [x] #103
    - [x] #199
- [x] merge feature branches *before* renaming
  - [x] #107
- [x] merge feature branches *after* renaming
  - [x] #407
  - [x] #408
- [x] ~Rename types with TM in the name, such as tmlogger and tmhash~
- [x] References to external services
     - [x] SECURITY.md: handle references to https://hackerone.com/cosmos and https://berlin.us4.list-manage.com/subscribe?u=431b35421ff7edcc77df5df10&id=3fe93307bc 
     - [x] Update code of conduct e-mail address
- [x] #324
- [x] QA
   - [x] #283
     - [x] cometbft/qa-infra#2
   - [x] #376
     - [x] #395

Only once we're really sure we're ready, can we cut the following releases:
- [x] Release `v0.34.27` to allow replacement of Tendermint Core `v0.34.26`
- [x] Release `v0.37.0-rc3` to allow replacement of Tendermint Core `v0.37.0-rc2` 
   - [x] #213 
   - [x] Merge changes from 0.37 into main's changelog.

**Comment by thanethomson** [comment]
Are there any other aspects of the rename missing at present? It seems to me like we're done here, so I'll close for now, but please reopen if anyone knows of anything else that we've missed.

#94 can be considered separate to this issue.
