### ISSUE TITLE
proto: Implement versioning

### ISSUE THREAD

**Issue by thanethomson** [cometbft/cometbft#95]
Relates to tendermint/tendermint#9197

Depends on #94

In order to better support integrators, we need to version our Protobuf definitions as per [Buf's guidelines](https://docs.buf.build/best-practices/module-development#module-layout). The goal here is to have:
- [x] Our Protobuf definitions in the `/proto` folder in the repo. https://github.com/cometbft/cometbft/pull/495
- [x] Our generated Protobuf Go code in a new `/api` folder in the repo. https://github.com/cometbft/cometbft/pull/495
- [x] Document how to translate protobuf messages across versions by annotating the `.proto` files
  - [x] #780

**Comment by mzabaluev** [comment]
After discussion with @thanethomson, I understand that we need to take care of snapshots of proto definitions going back to 0.34.

The proposed packaging versioning schema should look as follows:

* Any message definitions that were new in `v0.34.x` get packaged with the suffix `.v1` appended to their domain package name.
* Message definitions that have changed in subsequent release streams (`v0.37.x` and `main`/0.38 at the moment) in ways that introduce breaking changes to generated code in strictly typed languages (our primary concern being Go and Rust), are put into packages with incremental suffixes `.v2`, `.v3`, and so on. There is no direct correspondence between a package versioning suffix and any CometBFT protocol version; the suffixes are only to track evolution of message types.
* Messages newly introduced since 0.34 may land into `.v1` or later packages. This depends on which package's versioned namespace looks more natural considering type crosslinks and changes to adjacent message types in the same domain package.

**Comment by thanethomson** [comment]
> Regarding the output folder for the generated files, I'd prefer a single location including the ABCI stubs.
This would make buf.gen.yaml the single source of truth for the protobuf generation process, removing the tricky post-build Makefile actions.

This is precisely the idea.

**Comment by mzabaluev** [comment]
I've hit a problem in #495 with the `Wrap` API method that is manually implemented for generated variant types of `oneof` content fields for types like `Message`, e.g. in `consensus`.

This method ([permalink](https://github.com/cometbft/cometbft/blob/29765b988e45ea1488e7f1ce1bafd5aceb1cf132/proto/cometbft/consensus/v1/message.go#L21)), for example, has to be defined in `consensus/v1`, because `VoteSetBits` is defined in the corresponding proto package and the generated struct ends up in `consensus/v1/types.pb.go`:

```golang
func (m *VoteSetBits) Wrap() proto.Message {
	cm := &Message{}
	cm.Sum = &Message_VoteSetBits{VoteSetBits: m}
	return cm
}
```

However, it needs to produce a dynamically wrapped `Message` from `consensus/v2` for the value to actually work with other code that uses the latest version of `Message` (sorry I discovered it this late, being new to these parts, and the compiler could not help because the actual type is only checked dynamically). The problem is, we cannot use `v2` here because the code generated for `v2` itself imports `v1`: `v2.Message` refers to field types defined in `v1` to avoid duplicating their definitions in `v2`.

I can see the following ways to solve this:

1. Duplicate message types in versioned proto packages to eliminate cross-package references in such `oneof` message definitions. This is bad because duplication is made in the proto spec to work around issues in one particular language binding (Golang/gogoproto).
2. Rework the wrapper code to not use dynamic dispatch. The result will be less elegant and convenient to use, but I see only two call sites for `.Wrap()` in non-test code of CometBFT, so maybe that's OK.
3. Use compiler overrides or Golang-specific annotations to selectively affect package placement of generated code. I would need some expert help or extensive documentation digging for that. Does output for other types need to be similarly customized in order for the result to be somewhat consistent? Some users might want the legacy `v1` bindings to ensure backward compatibility, so we cannot just mash the latest definitions together in one happy unversioned Go package.
4. Create newtypes for `VoteSetBits` and the rest of the variant structs in the hand-coded `consensus` package, wrapping the generated types, and implement the `Wrapper` interface on these newtypes. Some amount of tedious coding is needed, perhaps exceeding the cost of option 2. In my view, this is only worth it the long run, if we generally want domain types to supplant proto-generated structs in the API.

**Comment by mzabaluev** [comment]
Resolved the above with a modification of the approach described in point 2.

**Comment by mzabaluev** [comment]
> The `/api` folder must effectively be a standalone Go module (i.e. have its own `go.mod` file, module `github.com/cometbft/cometbft/api`).

I don't see other `go.mod` files besides the one at the root of the repository, and package imports across the subdirectories work at least inside the CometBFT codebase. What are the benefits of the proposed organization? Do we get to cut the dependencies to only the ones required by the proto bindings? Can this work with the other `go.mod` remaining at the top, or should every Go source folder under root get its own `go.mod` with a trimmed down list of dependencies? I still need to hone my Go skills on this.

Meanwhile, I'm making the move of `*.pb.go` and associated manually-written method code into the `./api` folder, and it's the easiest thing to do in this whole enterprise.

**Comment by mzabaluev** [comment]
> What are the benefits of the proposed organization?

As we have established in a meeting about versioning, we want the proto-derived module versioned separately from module(s) that wrap or alias the proto-generated types into the versionless API for clients to work with.

**Comment by sergio-mena** [comment]
Moved to Q3. The goal is to coordinate with the main stake holders (IBC teams, SDK) to make sure they will plan their integration properly to minimize disruption. I will be doing that

**Comment by sergio-mena** [comment]
After examination with @mzabaluev all tasks here are complete. Some tasks that were remaining have been moved to the parent issue (#1330), in order to make tracking them easier.
